In [2]:
import torch

In [3]:
#inuts emeddings(simulataneously)
inputs = torch.tensor([
    [0.43, 0.15, 0.89], #Your       (x^1)
    [0.55, 0.87, 0.66], #journey    (x^2)
    [0.57, 0.85, 0.64], #starts     (x^3)
    [0.22, 0.58, 0.33], #with       (x^4)
    [0.77, 0.25, 0.10], #one        (x^5)
    [0.05, 0.80, 0.55], #step       (x^6)
])

In [4]:
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [5]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [6]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])

for i, x_i, in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)

attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [7]:
attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
attn_weights_2_tmp

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [8]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim = 0)

softmax_naive(attn_scores_2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [9]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)

In [10]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * x_i

context_vec_2

tensor([0.4419, 0.6515, 0.5683])

In [11]:
attn_scores = torch.empty(6, 6)


for i, x_i, in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)

attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [14]:
attn_scores = inputs @ inputs.T
attn_weights = torch.softmax(attn_scores, dim=1)
attn_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [15]:
all_context_vecs = attn_weights @ inputs
all_context_vecs

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

In [18]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [20]:
torch.manual_seed(123)

W_query = torch.rand(d_in, d_out, requires_grad=True)
W_key = torch.rand(d_in, d_out, requires_grad=True)
W_value = torch.rand(d_in, d_out, requires_grad=True)
W_query, W_key, W_value

(tensor([[0.2961, 0.5166],
         [0.2517, 0.6886],
         [0.0740, 0.8665]], requires_grad=True),
 tensor([[0.1366, 0.1025],
         [0.1841, 0.7264],
         [0.3153, 0.6871]], requires_grad=True),
 tensor([[0.0756, 0.1966],
         [0.3164, 0.4017],
         [0.1186, 0.8274]], requires_grad=True))

In [22]:
query_2 = x_2 @ W_query
keys = inputs @ W_key
value = inputs @ W_value
keys, value

(tensor([[0.3669, 0.7646],
         [0.4433, 1.1419],
         [0.4361, 1.1156],
         [0.2408, 0.6706],
         [0.1827, 0.3292],
         [0.3275, 0.9642]], grad_fn=<MmBackward0>),
 tensor([[0.1855, 0.8812],
         [0.3951, 1.0037],
         [0.3879, 0.9831],
         [0.2393, 0.5493],
         [0.1492, 0.3346],
         [0.3221, 0.7863]], grad_fn=<MmBackward0>))

In [23]:
keys_2 = keys[1]
attn_score_22 = torch.dot(keys_2, query_2)
attn_score_22

tensor(1.8524, grad_fn=<DotBackward0>)

In [25]:
attn_scores_2 = query_2 @ keys.T
attn_scores_2

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
       grad_fn=<SqueezeBackward4>)

In [27]:
d_k = keys.shape[1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k ** 0.5, dim=-1)
attn_weights_2  

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
       grad_fn=<SoftmaxBackward0>)

In [28]:
context_vec_2 = attn_weights_2 @ value
context_vec_2

tensor([0.3061, 0.8210], grad_fn=<SqueezeBackward4>)

In [29]:
import torch.nn as nn 

class SelfAttentionV1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = torch.rand(d_in, d_out, requires_grad=True)
        self.W_key = torch.rand(d_in, d_out, requires_grad=True)
        self.W_value = torch.rand(d_in, d_out, requires_grad=True)


    def forward(self, x):
        queries = inputs @ W_query
        keys = inputs @ W_key
        values = inputs @ W_value
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / d_k ** 0.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec

In [30]:
torch.manual_seed(123)
sa_v1 = SelfAttentionV1(d_in, d_out)
sa_v1.forward(inputs)

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)

In [31]:
import torch.nn as nn 

class SelfAttentionV2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = torch.nn.Linear(d_in, d_out, bias=qkv_bias)


    def forward(self, x):
        queries = self.W_query(inputs)
        keys = self.W_query(inputs)
        values = self.W_value(inputs)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / d_k ** 0.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec

In [33]:
torch.manual_seed(123)
sa_v2 = SelfAttentionV2(d_in, d_out)
sa_v2(inputs)

tensor([[-0.5287, -0.0976],
        [-0.5293, -0.1053],
        [-0.5293, -0.1052],
        [-0.5287, -0.1072],
        [-0.5287, -0.1038],
        [-0.5288, -0.1080]], grad_fn=<MmBackward0>)

In [34]:
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_query(inputs)
values = sa_v2.W_value(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / d_k ** 0.5, dim=-1)
attn_weights

tensor([[0.1895, 0.1660, 0.1663, 0.1562, 0.1674, 0.1547],
        [0.1694, 0.1690, 0.1690, 0.1633, 0.1652, 0.1642],
        [0.1696, 0.1690, 0.1689, 0.1632, 0.1652, 0.1640],
        [0.1642, 0.1683, 0.1682, 0.1664, 0.1654, 0.1673],
        [0.1732, 0.1675, 0.1675, 0.1628, 0.1663, 0.1627],
        [0.1623, 0.1688, 0.1687, 0.1670, 0.1650, 0.1683]],
       grad_fn=<SoftmaxBackward0>)

In [35]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [38]:
masked_simple = attn_weights * mask_simple
masked_simple

tensor([[0.1895, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1694, 0.1690, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1696, 0.1690, 0.1689, 0.0000, 0.0000, 0.0000],
        [0.1642, 0.1683, 0.1682, 0.1664, 0.0000, 0.0000],
        [0.1732, 0.1675, 0.1675, 0.1628, 0.1663, 0.0000],
        [0.1623, 0.1688, 0.1687, 0.1670, 0.1650, 0.1683]],
       grad_fn=<MulBackward0>)

In [39]:
row_sums = mask_simple.sum(dim=-1, keepdim=True)
mask_simple_norm = mask_simple / row_sums
mask_simple_norm

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]])

In [40]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
masked  = attn_scores.masked_fill(mask.bool(), -torch.inf)
masked

tensor([[ 0.2822,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.0954,  0.0921,    -inf,    -inf,    -inf,    -inf],
        [ 0.0974,  0.0917,  0.0914,    -inf,    -inf,    -inf],
        [ 0.0091,  0.0437,  0.0431,  0.0279,    -inf,    -inf],
        [ 0.1070,  0.0595,  0.0598,  0.0193,  0.0497,    -inf],
        [-0.0049,  0.0509,  0.0500,  0.0355,  0.0186,  0.0462]],
       grad_fn=<MaskedFillBackward0>)

In [41]:
attn_weights = torch.softmax(masked / keys.shape[-1] ** 0.5, dim=-1)
attn_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5006, 0.4994, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3342, 0.3329, 0.3328, 0.0000, 0.0000, 0.0000],
        [0.2462, 0.2523, 0.2521, 0.2494, 0.0000, 0.0000],
        [0.2069, 0.2000, 0.2001, 0.1944, 0.1986, 0.0000],
        [0.1623, 0.1688, 0.1687, 0.1670, 0.1650, 0.1683]],
       grad_fn=<SoftmaxBackward0>)

In [45]:
torch.manual_seed(123)
layer = nn.Dropout(.5)
layer(attn_weights)

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.6685, 0.6658, 0.6657, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5045, 0.5043, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.4000, 0.0000, 0.3888, 0.0000, 0.0000],
        [0.0000, 0.3376, 0.3374, 0.3340, 0.3300, 0.0000]],
       grad_fn=<MulBackward0>)

In [44]:
example = torch.ones(6, 6)
layer(example)

tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])

In [46]:
batch = torch.stack((inputs, inputs), dim=0)
batch

tensor([[[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]],

        [[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]]])

In [50]:
import torch.nn as nn 

class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.W_query = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer("mask", torch.triu(torch.ones(context_length, context_length), diagonal=1))


    def forward(self, x):
        b, num_tokens, d_in = x.shape
        queries = self.W_query(x)
        keys = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.transpose(1, 2)
        attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)
        attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)
        context_vec = attn_weights @ values
        return context_vec

In [51]:
torch.manual_seed(789)
ca = CausalAttention(d_in, d_out, context_length = batch.shape[1], dropout = 0.0)
ca(batch)

tensor([[[-0.0872,  0.0286],
         [-0.1020,  0.0554],
         [-0.1019,  0.0687],
         [-0.0992,  0.0517],
         [-0.0556,  0.1070],
         [-0.0832,  0.0621]],

        [[-0.0872,  0.0286],
         [-0.1020,  0.0554],
         [-0.1019,  0.0687],
         [-0.0992,  0.0517],
         [-0.0556,  0.1070],
         [-0.0832,  0.0621]]], grad_fn=<UnsafeViewBackward0>)

In [ ]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self,d_in, d_out, context_length = batch.shape[1], dropout = 0.0, qkv_bias = False, num_heads=2):
        super().__init__()
        self.heads = nn.ModuleList([
            CausalAttention(d_in, d_out, context_length = batch.shape[1], dropout = 0.0) for _ in range(num_heads)
            ])
    def forward(self, x):
        head(x)
