In [1]:
import torch
torch.__version__

'2.7.1+cu128'

In [2]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
#indexing tensors
a[-1].item()

11

In [7]:
a[0] = 100
a

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [9]:
b = a[2:4] #Срезы не создают новых тензоров а лишь делают новое предсталвение старых, то есть изменения в тензоре b скажутся и на тензоре a
b

tensor([2, 3])

In [10]:
a[3:]

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a[:4] = torch.tensor([-1, -2, -3, -4], dtype=torch.int32)
a

tensor([-1, -2, -3, -4,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
x = torch.tensor([(1, 2, 3), (10, 20, 30), (100, 200, 300)], dtype=torch.int32)
x

tensor([[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]], dtype=torch.int32)

In [16]:
x[1, 1].item()

20

In [19]:
a = torch.arange(1, 82).reshape(3, 3, 3, 3) #Тут получается матрица 3х3 из матриц 3х3
a[:, 1, :, :]

tensor([[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]])

In [20]:
a[..., 2, 2]

tensor([[ 9, 18, 27],
        [36, 45, 54],
        [63, 72, 81]])

In [21]:
a = torch.arange(1, 9)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
b = a[[0, 1, 7, 3, 0]]
b

tensor([1, 2, 8, 4, 1])

In [65]:
indx = torch.randint(8, (1,9)).ravel()
a[indx]

tensor([7, 1, 3, 8, 2, 5, 5, 3, 5])

In [66]:
index = a > 4
a[index]

tensor([5, 6, 7, 8])