In [3]:
import torch

In [4]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
a ** 3

tensor([ 1.,  8., 27.])

In [5]:
b = torch.tensor([3, 4, 5], dtype=torch.int32)
a ** b

tensor([  1.,  16., 243.])

In [6]:
a = torch.arange(1, 19).reshape(3, 3, 2)
b = torch.ones(3, 2)
a - b

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.]]])

In [7]:
a = torch.tensor([1, 2, 3, 10, 20, 30], dtype=torch.float32)
a.std()

tensor(11.7303)

In [8]:
tensor = torch.arange(15).reshape(3, 5) + torch.randn(3, 5)
#torch.abs(tensor) - модуль от элементов тензора 
#torch.amax(tensor) - максимальное значение в тензоре
#torch.amin(tensor) - минимальное значение в тензоре
#torch.argmax(tensor) - индекс максимального знаечния в тензоре 
#torch.argmin(tensor) - индекс минимального значения в тензоре
#torch.round(tensor) - округление элементов до ближайшего целого значения 
#torch.mean(tensor) - среднее значение тензора
#torch.log(tensor) - натуральный логарифм элементов тензора
#torch.log2(tensor) - логарифм по основанию 2
#torch.log10(tensor) - логарифм по основанию 10


In [9]:
#torch.median(tensor) - медиана тензора
#torch.var(tensor) - дисперсия значений тензора
#torch.std(tensor) - стандартное отклонение значений тензора
#torch.corrcoef(tensor) - линейный коэффициент корреляции Пирсона
#torch.cov(tensor) - ковариация 
tensor.cov()

tensor([[3.8109, 4.2845, 1.7986],
        [4.2845, 7.5062, 3.0108],
        [1.7986, 3.0108, 1.7498]])

In [ ]:
a = torch.randn(3, 3)
b = torch.randn(3, 3)
c = a @ b
c

tensor([[-0.6202, -0.5515, -0.8083],
        [ 0.5004, -1.1143, -0.9713],
        [-0.8713, -1.5936,  1.7474]])

In [ ]:
bx = torch.rand(7, 3, 5)
by = torch.randn(7, 5, 4)
bc = torch.bmm(bx, by)
bc

RuntimeError: batch1 must be a 3D tensor