In [ ]:
import torch
tz = torch.zeros(2, 3) #Заполнение нулями
tz

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
t = torch.ones(2, 3) #Заполнение единицами
t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.eye(3) #Единичная матрица 3х3

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.eye(2, 5) #Единичная матрица 2х5

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [ ]:
torch.full((2, 4), 5) #Заполнение матрицы 2х4 значением 5

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]])

In [ ]:
torch.arange(10) #Заполнение тензора значениями от 0 до value

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(2, 0, -0.1) #Заполнение тензора значениями от l_value до r_value с шагом step

tensor([2.0000, 1.9000, 1.8000, 1.7000, 1.6000, 1.5000, 1.4000, 1.3000, 1.2000,
        1.1000, 1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000,
        0.2000, 0.1000])

In [ ]:
torch.linspace(1, 5, 9) #Заполнение тензора значениями, соответствующим равным разделениям диапазона на value частей

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000])

In [ ]:
torch.rand(2, 3) #Заполнение тензора значениями [0; 1] равномерного распределения 

tensor([[0.4439, 0.9830, 0.8461],
        [0.2026, 0.6910, 0.9496]])

In [24]:
torch.randn(2, 3) #Заполнение тензора значениями из нормального распределения с нулевым средним и единичной дисперсией

tensor([[ 0.4696,  0.5538,  0.7766],
        [-0.3151,  1.0686,  2.3855]])

In [ ]:
torch.manual_seed(42) #Псевдо-рандом
torch.randn(2, 3)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

In [ ]:
#name_ - inplace(mutable) метод изменяет текущий тензор, не создавая нового
#name - immutable метод не меняет текущий тензор, а создаёт новый
x = torch.FloatTensor(2, 4)
x.fill_(1)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:

#Представления тензоров 
#reshape = view
t = torch.randn(27)
t = t.reshape(3, 3, 3)
t

tensor([[[-0.7360, -0.8371, -0.9224],
         [ 1.8113,  0.1606,  0.3672],
         [ 0.1754,  1.3852,  1.3835]],

        [[-1.2024,  0.7078, -1.3407],
         [-0.5854,  0.5362,  0.5246],
         [ 1.1412,  0.0516,  0.7281]],

        [[-0.7106, -1.0495,  0.6039],
         [-1.7223, -0.8278,  1.3347],
         [ 0.4835, -0.1976,  1.2683]]])

In [ ]:
#Изменяет размер тензора
t.resize_(2, 6)

tensor([[-0.7360, -0.8371, -0.9224,  1.8113,  0.1606,  0.3672],
        [ 0.1754,  1.3852,  1.3835, -1.2024,  0.7078, -1.3407]])

In [ ]:
#Тензор в вектор
t.ravel()

tensor([-0.7360, -0.8371, -0.9224,  1.8113,  0.1606,  0.3672,  0.1754,  1.3852,
         1.3835, -1.2024,  0.7078, -1.3407])

In [ ]:
#Меняет оси местами(что-то по типу транспонирования)
t.permute(1, 0)

tensor([[-0.7360,  0.1754],
        [-0.8371,  1.3852],
        [-0.9224,  1.3835],
        [ 1.8113, -1.2024],
        [ 0.1606,  0.7078],
        [ 0.3672, -1.3407]])

In [ ]:
#Траспонирование
t.mT

tensor([[-0.7360,  0.1754],
        [-0.8371,  1.3852],
        [-0.9224,  1.3835],
        [ 1.8113, -1.2024],
        [ 0.1606,  0.7078],
        [ 0.3672, -1.3407]])

In [54]:
x_test = torch.arange(32).view(8, 2, 2)
x_test.shape

torch.Size([8, 2, 2])

In [ ]:
#unsqueeze - добавление оси
x_test = torch.unsqueeze(x_test, dim = 0)
x_test.shape

torch.Size([1, 8, 2, 2])

In [59]:
x_test = torch.squeeze(x_test)
x_test.shape

torch.Size([8, 2, 2])